### ISSUE TITLE
프로젝트 주제

### ISSUE THREAD

**Issue by HyeunKim** [OSSorganization/management_employee#1]
프로젝트를 어떤 방향으로 주제를 잡으면 좋을까요?

**Comment by 21900162** [comment]
직원 관리하는 프로젝트이니까 직원들 출퇴근 관련 프로젝트는 어떨까요?

**Comment by HyeunKim** [comment]
좋아요! 그러면 직원 한 명 입장에서 출근과 퇴근을 개인적으로 체크하는 것보다 관리자 입장에서 여러 직원들의 출퇴근을 관리하는 시스템으로 하는 게 맞을까요?

**Comment by 21900162** [comment]
네! 좋은 것 같아요

**Comment by HyeunKim** [comment]
그럼 주제는 '관리자 입장의 출퇴근 관리 시스템'으로 결론나는 것으로 하겠습니다!
