### ISSUE TITLE
프로젝트 기능

### ISSUE THREAD

**Issue by 21900162** [OSSorganization/management_employee#2]
프로젝트 안에 어떤 기능들을 만들어 볼까요?

**Comment by 21900162** [comment]
직원들 출퇴근 시간을 기록하는 기능 필요할 것 같아요

**Comment by 21900162** [comment]
그리고 출퇴근 시간 계산해서 일급 계산하는 기능도 있으면 좋을 것 같아요

**Comment by HyeunKim** [comment]
넵 그러면 일급이나 주급 월급을 관리자가 입력되는거에 따라 계산해서 저장하고 일급 주급 월급 중에 검색할 것을 고르면 결과 나오는 것도 좋을 것 같아요!

**Comment by 21900162** [comment]
혹시 주급이나 월급은 한 사람이 하루 일한 걸 계산해서 구현하는 걸까요?

**Comment by HyeunKim** [comment]
앗 넵 저는 일단 한 사람에 대해 출근시간과 퇴근시간을 기록하면, 그 사람에 대한 일급이 먼저 나올테고 이에 따라서 주급이랑 월급은 미리 예상되어서 같이 나온다고 생각했습니다!

**Comment by HyeunKim** [comment]
예를 들어 일급이 10,000원으로 나왔다면 주급이 궁금할 경우 다른 메뉴에서 관리자가 주급을 체크하고 이 사람은 주 3일 일한다고 체크하고, 주급을 보고싶다고 체크하면 '예상 주급: 30,000원'이라고 나오는 것이죠.

**Comment by HyeunKim** [comment]
그런데 생각해보니 이 기능은 예상하는 기능이기도 하고 전체 시스템에서 필수적인 요소가 아니라 부가적인 거라서 나중에 구현 가능성이나 시간 보고 만드시거나 빼셔도 될 것 같아요!!

**Comment by 21900162** [comment]
넵!! 저는 일단 시간별로 직원들이 몇시에 출근했는지 보여주는 기능 생각해봤어요
예를 들면 7시에서 8시 사이에 출근한 직원은 누군지 보여주는? 기능 생각해봤습니다

**Comment by HyeunKim** [comment]
아까 말씀하신 것처럼 각 사람을 검색해서 하루 출퇴근을 입력하면 그 하루에 대한 일급만 결과로 나오는 것까지 필수적으로 구현하구요 !

**Comment by HyeunKim** [comment]
아하 여러명 사람들 출퇴근 통계를 나타내는건가요? 좋은 것 같습니다!

**Comment by 21900162** [comment]
그러면 일단 지금까지 기본적으로 CRUD기능 구현하고 출근 시간이나 퇴근 시간 보여주는 기능까지 나왔네요

**Comment by 21900162** [comment]
그리고 이름을 검색해서 해당 직원 출퇴근 시간 보여주는 기능도 있으면 좋을 것 같아요

**Comment by HyeunKim** [comment]
앗 CRUD 기능 중 R에서 출퇴근 시간 보여주는 것이 아닌가요?

**Comment by HyeunKim** [comment]
아 제가 잘못이해했네요

**Comment by 21900162** [comment]
아 저는 아까 말한 시간별로 누가 출근했는지 보여주는 기능? 의미했었습니다

**Comment by 21900162** [comment]
그리고 직원들 출퇴근 시간을 파일에 저장하고 불러오는 기능도 넣어볼까요?

**Comment by HyeunKim** [comment]
넵넵 그럼 지금까지 나온 거 간단하게 정리해볼게요!!

1. 직원 한 명 출퇴근 시간 입력
2. 입력된 모든 직원들 출퇴근 시간 보여주기
3. 직원 한 명 출퇴근 시간 수정
4. 직원 한 명 출퇴근 파트 삭제
5. 시간별 출퇴근 시간 통계 보여주기(ex. 7시 타임에 누가 출근했는지/5시에 누가 퇴근했는지)
6. 해당 직원 출퇴근 시간 검색(A 직원의 출퇴근 시간이 언제인지 알려줌)
7. 해당 직원 일급 검색(A 직원 오늘 하루 일급은 얼마인지 알려줌)

**Comment by HyeunKim** [comment]
추가로 지금까지 입력되어 있는 직원들 출퇴근 시간들을 텍스트 파일에 저장하면 좋을 것 같아요!

**Comment by HyeunKim** [comment]
이 프로그램을 시작했을 때 위 저장해뒀던 텍스트 파일의 내용을 불러와서 계속 이어서 출퇴근 리스트를 추가할 수 있도록 불러오기 기능도 같이 추가하는 건 어떨까요?

**Comment by 21900162** [comment]
네! 좋은거 같아요 
그러면 입력 받을 때는
직원이름:
출근 시간:
퇴근 시간:
이렇게 할까요? 더 추가할 내용 있을까요?

**Comment by HyeunKim** [comment]
아 중간에 휴게시간이 있을 수 있으니(일급 계산에서 빠져야하는 시간) 이부분에 대해 추가하는 것은 어떤가요? 마지막에 '휴게 시간 : '을 더하는 거죠!

**Comment by 21900162** [comment]
그리고 날짜도 들어가면 좋을 것 같네요

**Comment by HyeunKim** [comment]
네! 그러면 이때 날짜와 시간은 다 정수형 변수로 입력받을까요? 날짜는 20220430 시간은 0730 이렇게요
아니면 문자열로 받을까요? 날짜는 2022-04-30 시간은 07:30

**Comment by HyeunKim** [comment]
아 그리고 모든 일급은 최저시급을 받는다는 가정하에 계산되도록 할까요? 아니면 시급이 얼마인지에 대해서도 입력받는 게 나을까요?

**Comment by 21900162** [comment]
최저시급 받는걸로 하면 좋을 것 같아요

**Comment by HyeunKim** [comment]
넵! 그러면 저희 지금까지 정리하면

### [ 구현할 기능 10가지 ]
1. 직원 한 명 출퇴근 시간 입력
2. 입력된 모든 직원들 출퇴근 시간 보여주기
3. 직원 한 명 출퇴근 시간 수정
4. 직원 한 명 출퇴근 파트 삭제
5. 지금까지의 내용 텍스트 파일에 저장
6. 저장된 텍스트 파일 내용 불러오기
7. 시간별 출근 시간 통계 보여주기(ex. 7시 타임에 누가 출근했는지)
8. 시간별 퇴근 시간 통계 보여주기(ex. 5시에 누가 퇴근했는지)
9. 해당 직원 출퇴근 시간 검색(A 직원의 출퇴근 시간이 언제인지 알려줌)
10. 해당 직원 일급 검색(A 직원 오늘 하루 일급은 얼마인지 알려줌)

### [ 메뉴 1 에서 입력받을 때 메시지 ]
1. 날짜 : 
2. 직원 이름 : 
3. 출근 시각 : 
4. 퇴근 시각 : 
5. 휴게 시간 : 

이렇게가 맞을까요!?

**Comment by 21900162** [comment]
네 맞아요!
