### ISSUE TITLE
데이터 저장할 구조체 구조

### ISSUE THREAD

**Issue by HyeunKim** [OSSorganization/management_employee#3]
직원들 출퇴근 관리 프로그램을 위해서, 저장되어야 할 직원별 데이터들은 어떻게 구체적으로 구현하면 좋을까요?

**Comment by 21900162** [comment]
일단은 출근시간, 퇴근시간, 휴식 시간이 몇시 몇분인지 int로 정의해야하지 않을 까요

**Comment by 21900162** [comment]
string name;
int month, day;
int in_hour, in_minute;
int out_hour, out_minute;
쉬는 시간은 어떻게 입력을 받을까요?

**Comment by HyeunKim** [comment]
네 각 시각의 시/분을 다 정수형 변수에 저장하면 될 것 같아요!

**Comment by HyeunKim** [comment]
아 저희 사용하는 언어에 따라 string형이 없을 수도 있을 것 같은데 혹시 저희 무슨 언어로 작업하면 좋을까요?? 선호하시는 언어가 있나요?

**Comment by HyeunKim** [comment]
쉬는 시간에 대해서는 rest 단어를 사용해볼까요!? rest_hour, rest_minute 어떤가요?

**Comment by HyeunKim** [comment]
혹시 c 언어로 작업한다면

typedef struct{
    char name[100];
    int month, day;
    int in_hour, in_minute;
    int out_hour, out_minute;
    int rest_hour, rest_minute;
} Employee;

하면 될 것 같습니다!

**Comment by 21900162** [comment]
네!!
각자 구현할 함수 나눠볼까요?

**Comment by 21900162** [comment]
그리고 구조체 배열로 만들어서 구현해볼까요?

**Comment by HyeunKim** [comment]
구조체 배열로 구현하는 것 좋은 것 같습니다! 각자 역할 분담을 새로운 이슈 만들어놨어서 거기서 얘기 나눠봐요 !

**Comment by HyeunKim** [comment]
그럼 c언어로 작성하고, 위와 같은 구조체를 가지고 함수 구체적으로 구현해봅시다
