### ISSUE TITLE
역할 분담

### ISSUE THREAD

**Issue by HyeunKim** [OSSorganization/management_employee#4]
구현해야 할 기능이 다음과 같은데 어떻게 나눌까요?

### [ 구현해야 할 기능 ]
1. 직원 한 명 출퇴근 시간 입력
2. 입력된 모든 직원들 출퇴근 시간 보여주기
3. 직원 한 명 출퇴근 시간 수정
4. 직원 한 명 출퇴근 파트 삭제
5. 지금까지의 내용 텍스트 파일에 저장
6. 저장된 텍스트 파일 내용 불러오기
7. 시간별 출근 시간 통계 보여주기(ex. 7시 타임에 누가 출근했는지)
8. 시간별 퇴근 시간 통계 보여주기(ex. 5시에 누가 퇴근했는지)
9. 해당 직원 출퇴근 시간 검색(A 직원의 출퇴근 시간이 언제인지 알려줌)
10. 해당 직원 일급 검색(A 직원 오늘 하루 일급은 얼마인지 알려줌)

5번과 6번은 같은 사람이 연결해서 작업하면 좋을 것 같아서, 
1-6 / 7-10 으로 나눌까요?

**Comment by HyeunKim** [comment]
7-10번 하는 사람이 메인 함수까지 하면 될 것 같아요!

**Comment by 21900162** [comment]
네!! 제가 1-6까지 해도 될까요?

**Comment by HyeunKim** [comment]
네 좋습니다! 그러면 제가 뒤 7-10과 메인 함수 부분 맡을게요!
