### ISSUE TITLE
Readme.md 파일 역할분담

### ISSUE THREAD

**Issue by 21900162** [OSSorganization/management_employee#7]

**Comment by HyeunKim** [comment]
- mini project 주제
- mini project 에 대한 소개
- image(pixabay 등 무료 이미지 활용)
- mini project 가 가지고 있는 대략적인 기능 설명
- 개발환경 및 언어
- 팀소개 및 팀원이 맡은 역할

**Comment by HyeunKim** [comment]
제가 뒤에 3개 하겠습니다!

**Comment by 21900162** [comment]
그러면 앞에 3개 제가 하겠습니다!
