### ISSUE TITLE
함수 구현

### ISSUE THREAD

**Issue by 21900162** [OSSorganization/management_employee#8]

**Comment by 21900162** [comment]
사용자한테 시간은 24시간 기준으로 입력 받을께요!
ex) 17:10

**Comment by 21900162** [comment]
그리고 delete하면 month의 값을 0으로 지정하겠습니다.

**Comment by 21900162** [comment]
serachTime함수에서 
if(month == -1) continue -> if(month ==0) continue로 바꿔주실 수 있나요?

**Comment by HyeunKim** [comment]
퇴근 시간에 대한 통계가 출력되지 않는 오류를 수정했습니다!

**Comment by HyeunKim** [comment]
calculateDailyWage 함수, searchTime 함수에서 month 값이 0으로 되도록 수정했습니다.

**Comment by HyeunKim** [comment]
출퇴근 통계 함수에서, 정보를 삭제했음에도 출퇴근 통계에는 반영이 안되던 오류를 고쳐 삭제된 정보는 통계에 나타나지 않게 수정했습니다.

**Comment by HyeunKim** [comment]
현재 출퇴근 통계를 보여줄 땐 직원의 출퇴근 날짜와 상관없이 시간으로만 보여주고 있는데, 관리자에게 보고 싶은 날짜를 입력받아 해당 날짜에만 시간별로 통계를 보여주도록 할까요? 아니면 지금처럼 날짜 상관없이 다 보여주게 할까요?

현재 예시)
A 직원이 5/7일 06:00 출근, B 직원이 5/8일 06:00 출근시 출근 통계 보는 메뉴를 선택하면 두 직원이 모두 6시~7시에 출근한 것으로 나옴.

의견 예시)
A 직원이 5/7일 06:00 출근, B 직원이 5/8일 06:00 출근 상황에서, 출근 통계를 보는 메뉴를 선택하면 먼저 보고싶은 날짜를 선택하게 하고, 이때 관리자가 5/7을 입력하면 5/7일에 입력된 A 직원만 6~7시에 출근한 것으로 나옴.

아니면 메뉴 선택시 처음에 원하는 날짜가 있는지, 혹은 날짜와 상관없는 통계를 보고싶은지 묻고 이에 따라 위의 두 예시가 적절하게 나오도록 할까요?

**Comment by HyeunKim** [comment]
일단은 다 가능하게 마지막 모든 경우 가능하게 코드를 구성하도록 하겠습니다!

**Comment by 21900162** [comment]
두 예시가 나오도록 하면 더 좋을 것 같아요!

**Comment by HyeunKim** [comment]
넵 알겠습니다!!
